spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testjdbc?serverTimezone=GMT%2B8
    username: root
    password: shiyan831529
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: utf-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181